# version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    networks:
      - ridenitt-network
  
networks:
  ridenitt-network:
    external: false